### ISSUE TITLE
node.js example

### ISSUE THREAD

**Issue by Downchuck** [dchest/tweetnacl-auth-js#1]
Took me a couple of attempts, landed on this:

```
var nacl = require('tweetnacl');
nacl.auth = require('tweetnacl-auth');
```

**Comment by dchest** [comment]
Strictly speaking, you can also import it to any variable you like and then use it:

```
var naclAuth = require('tweetnacl-auth');

naclAuth.auth(message, key)
```

but, yes, as a kind of extension to `nacl`, it's nice to put it into the `nacl` object, as it does when not under a CommonJS environment.
